### ISSUE TITLE
Carpentries Labs

### ISSUE THREAD

**Issue by sstevens2** [dme26/docker-introduction#12]
Hi @jduckles and @dme26, 

On a call today and I'm thinking maybe we should make a goal to get the lessons into a state we are pretty happy with by a specific date and submit them to Carpentries Labs for review.

https://github.com/carpentrieslab/proposals

What do you think?
Sarah

**Comment by jduckles** [comment]
I think that would be a great idea! I hadn't heard of Carpentries labs, did I miss this in the Newsletter or on the Blog? Where did you hear about it @sstevens2?

**Comment by dme26** [comment]
Sounds great! Apologies for the delay in reply on my side: slightly crazy time. I'll be using this lesson in a few weeks for a lab, though, so that should focus efforts.

**Comment by sstevens2** [comment]
I'd heard about it from Erin Becker when I taught DC genomics in AZ a month or so ago but then also again in the recent Member Organization Council  meeting.  I think it is still in progress but it sounded like they might be interested in using this as a test case.

**Comment by dme26** [comment]
Can I just check, @sstevens2 that the carpentries-incubator shift of the docker-introduction will cover immediate needs, either through:
- review happening in the incubator, or 
- through us being able to add relevant carpentries-lab requests from there? 

If so, then we can probably close this issue here...

**Comment by sstevens2** [comment]
Yes, this is the shift to incubator (I think it got renamed from labs).  I think that addresses this issue.
