### ISSUE TITLE
Switch python test and csv to slim

### ISSUE THREAD

**Issue by sstevens2** [dme26/docker-introduction#3]
When I tested this with a small group they were surprised at how big the python:3 image was and I was worried with my class of 30 (turned out to be more like 50), the wifi would struggle to download the ~1GB image for everyone.  I switched it to `python:3-slim` and everything seemed to work well still.

**Comment by dme26** [comment]
Great—thanks! I've just quickly run through the 05-creating-container-images.md page to update Dockerfile FROMs and the output blocks from Docker that changed (a little) as a consequence.
